#!/bin/bash
# find . \( -name "*.c" -or -name "*.cpp" -or -name "*.h" -or -name "*.java" -or -name "*.py" \) -printf "cp ../../cpsc474_cribbage/code/%p %p\n"
# then manually remove my_policy and solution files

cp ../../cpsc474_cribbage/code/./c/c_cribbage.cpp ./c/c_cribbage.cpp
cp ../../cpsc474_cribbage/code/./c/c_cribbage.h ./c/c_cribbage.h
cp ../../cpsc474_cribbage/code/./c/c_greedy.c ./c/c_greedy.c
cp ../../cpsc474_cribbage/code/./c/c_greedy.h ./c/c_greedy.h
cp ../../cpsc474_cribbage/code/./c/c_policy.cpp ./c/c_policy.cpp
cp ../../cpsc474_cribbage/code/./c/c_policy.h ./c/c_policy.h
cp ../../cpsc474_cribbage/code/./c/greedy.h ./c/greedy.h
cp ../../cpsc474_cribbage/code/./c/card.cpp ./c/card.cpp
cp ../../cpsc474_cribbage/code/./c/card.h ./c/card.h
cp ../../cpsc474_cribbage/code/./c/character_suits.cpp ./c/character_suits.cpp
cp ../../cpsc474_cribbage/code/./c/character_suits.h ./c/character_suits.h
cp ../../cpsc474_cribbage/code/./c/combinations.cpp ./c/combinations.cpp
cp ../../cpsc474_cribbage/code/./c/combinations.h ./c/combinations.h
cp ../../cpsc474_cribbage/code/./c/c_utility.h ./c/c_utility.h
cp ../../cpsc474_cribbage/code/./c/deck.cpp ./c/deck.cpp
cp ../../cpsc474_cribbage/code/./c/deck.h ./c/deck.h
cp ../../cpsc474_cribbage/code/./c/game.cpp ./c/game.cpp
cp ../../cpsc474_cribbage/code/./c/game.h ./c/game.h
cp ../../cpsc474_cribbage/code/./c/hand.cpp ./c/hand.cpp
cp ../../cpsc474_cribbage/code/./c/hand.h ./c/hand.h
cp ../../cpsc474_cribbage/code/./c/history.cpp ./c/history.cpp
cp ../../cpsc474_cribbage/code/./c/history.h ./c/history.h
cp ../../cpsc474_cribbage/code/./c/ordered_ranks.cpp ./c/ordered_ranks.cpp
cp ../../cpsc474_cribbage/code/./c/ordered_ranks.h ./c/ordered_ranks.h
cp ../../cpsc474_cribbage/code/./c/policy.cpp ./c/policy.cpp
cp ../../cpsc474_cribbage/code/./c/policy.h ./c/policy.h
cp ../../cpsc474_cribbage/code/./c/rank.cpp ./c/rank.cpp
cp ../../cpsc474_cribbage/code/./c/rank.h ./c/rank.h
cp ../../cpsc474_cribbage/code/./c/utility.cpp ./c/utility.cpp
cp ../../cpsc474_cribbage/code/./c/utility.h ./c/utility.h
cp ../../cpsc474_cribbage/code/./c/c_utility.c ./c/c_utility.c
cp ../../cpsc474_cribbage/code/./c/greedy.cpp ./c/greedy.cpp
cp ../../cpsc474_cribbage/code/./c/test_cribbage_c.cpp ./c/test_cribbage_c.cpp
cp ../../cpsc474_cribbage/code/./cpp/c_utility.c ./cpp/c_utility.c
cp ../../cpsc474_cribbage/code/./cpp/c_utility.h ./cpp/c_utility.h
cp ../../cpsc474_cribbage/code/./cpp/card.cpp ./cpp/card.cpp
cp ../../cpsc474_cribbage/code/./cpp/card.h ./cpp/card.h
cp ../../cpsc474_cribbage/code/./cpp/character_suits.cpp ./cpp/character_suits.cpp
cp ../../cpsc474_cribbage/code/./cpp/character_suits.h ./cpp/character_suits.h
cp ../../cpsc474_cribbage/code/./cpp/combinations.cpp ./cpp/combinations.cpp
cp ../../cpsc474_cribbage/code/./cpp/combinations.h ./cpp/combinations.h
cp ../../cpsc474_cribbage/code/./cpp/deck.cpp ./cpp/deck.cpp
cp ../../cpsc474_cribbage/code/./cpp/deck.h ./cpp/deck.h
cp ../../cpsc474_cribbage/code/./cpp/game.cpp ./cpp/game.cpp
cp ../../cpsc474_cribbage/code/./cpp/game.h ./cpp/game.h
cp ../../cpsc474_cribbage/code/./cpp/greedy.cpp ./cpp/greedy.cpp
cp ../../cpsc474_cribbage/code/./cpp/greedy.h ./cpp/greedy.h
cp ../../cpsc474_cribbage/code/./cpp/hand.cpp ./cpp/hand.cpp
cp ../../cpsc474_cribbage/code/./cpp/hand.h ./cpp/hand.h
cp ../../cpsc474_cribbage/code/./cpp/history.cpp ./cpp/history.cpp
cp ../../cpsc474_cribbage/code/./cpp/history.h ./cpp/history.h
cp ../../cpsc474_cribbage/code/./cpp/ordered_ranks.cpp ./cpp/ordered_ranks.cpp
cp ../../cpsc474_cribbage/code/./cpp/ordered_ranks.h ./cpp/ordered_ranks.h
cp ../../cpsc474_cribbage/code/./cpp/policy.cpp ./cpp/policy.cpp
cp ../../cpsc474_cribbage/code/./cpp/policy.h ./cpp/policy.h
cp ../../cpsc474_cribbage/code/./cpp/rank.cpp ./cpp/rank.cpp
cp ../../cpsc474_cribbage/code/./cpp/rank.h ./cpp/rank.h
cp ../../cpsc474_cribbage/code/./cpp/test_cribbage.cpp ./cpp/test_cribbage.cpp
cp ../../cpsc474_cribbage/code/./cpp/utility.cpp ./cpp/utility.cpp
cp ../../cpsc474_cribbage/code/./cpp/utility.h ./cpp/utility.h
cp ../../cpsc474_cribbage/code/./java/TestCribbage.java ./java/TestCribbage.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/Card.java ./java/edu/yale/cs/cpsc474/Card.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CardRank.java ./java/edu/yale/cs/cpsc474/CardRank.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CharacterSuits.java ./java/edu/yale/cs/cpsc474/CharacterSuits.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/Combinatorics.java ./java/edu/yale/cs/cpsc474/Combinatorics.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CompoundPolicy.java ./java/edu/yale/cs/cpsc474/CompoundPolicy.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CribbageCard.java ./java/edu/yale/cs/cpsc474/CribbageCard.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CribbageDeck.java ./java/edu/yale/cs/cpsc474/CribbageDeck.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CribbageHand.java ./java/edu/yale/cs/cpsc474/CribbageHand.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CribbagePolicy.java ./java/edu/yale/cs/cpsc474/CribbagePolicy.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/Deck.java ./java/edu/yale/cs/cpsc474/Deck.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/EvaluationResults.java ./java/edu/yale/cs/cpsc474/EvaluationResults.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/GreedyPegger.java ./java/edu/yale/cs/cpsc474/GreedyPegger.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/GreedyThrower.java ./java/edu/yale/cs/cpsc474/GreedyThrower.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/IntegerRanks.java ./java/edu/yale/cs/cpsc474/IntegerRanks.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/IterTools.java ./java/edu/yale/cs/cpsc474/IterTools.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/KeepPolicy.java ./java/edu/yale/cs/cpsc474/KeepPolicy.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/Logger.java ./java/edu/yale/cs/cpsc474/Logger.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/MoreArrays.java ./java/edu/yale/cs/cpsc474/MoreArrays.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/NullLogger.java ./java/edu/yale/cs/cpsc474/NullLogger.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/OrderedRanks.java ./java/edu/yale/cs/cpsc474/OrderedRanks.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/PegPolicy.java ./java/edu/yale/cs/cpsc474/PegPolicy.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/PeggingHistory.java ./java/edu/yale/cs/cpsc474/PeggingHistory.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/PrintStreamLogger.java ./java/edu/yale/cs/cpsc474/PrintStreamLogger.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/RandomPegger.java ./java/edu/yale/cs/cpsc474/RandomPegger.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/RandomThrower.java ./java/edu/yale/cs/cpsc474/RandomThrower.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/RankType.java ./java/edu/yale/cs/cpsc474/RankType.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/SuitType.java ./java/edu/yale/cs/cpsc474/SuitType.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/CribbageGame.java ./java/edu/yale/cs/cpsc474/CribbageGame.java
cp ../../cpsc474_cribbage/code/./java/edu/yale/cs/cpsc474/GameAction.java ./java/edu/yale/cs/cpsc474/GameAction.java
cp ../../cpsc474_cribbage/code/./python/cribbage.py ./python/cribbage.py
cp ../../cpsc474_cribbage/code/./python/deck.py ./python/deck.py
cp ../../cpsc474_cribbage/code/./python/pegging.py ./python/pegging.py
cp ../../cpsc474_cribbage/code/./python/policy.py ./python/policy.py
cp ../../cpsc474_cribbage/code/./python/scoring.py ./python/scoring.py
cp ../../cpsc474_cribbage/code/./python/test_cribbage.py ./python/test_cribbage.py
